USE ProjectD52021F
GO

CREATE TABLE [dbo].[BipolarDepression_PatientLevelVars](
	[PatientDurableKey] [bigint] NULL,
	[BirthDate] [date] NULL,
	[DeathDate] [date] NULL,
	[FirstRace] [nvarchar](300) NULL,
	[SecondRace] [nvarchar](300) NULL,
	[ThirdRace] [nvarchar](300) NULL,
	[FourthRace] [nvarchar](300) NULL,
	[FifthRace] [nvarchar](300) NULL,
	[Ethnicity] [nvarchar](300) NULL,
	[Sex] [nvarchar](300) NULL,
	[SexAssignedAtBirth] [nvarchar](300) NULL,
	[GenderIdentity] [nvarchar](300) NULL,
	[PreferredLanguage] [nvarchar](300) NULL,
	[ValidatedStateOrProvince_X] [nvarchar](300) NULL,
	[ValidatedStateOrProvinceAbbreviation_X] [nvarchar](300) NULL,
	[MaritalStatus] [nvarchar](300) NULL,
	[SviHouseholdCharacteristicsPctlRankByZip2020_X] [numeric](10, 4) NULL,
	[SviHouseholdCompositionPctlRankingByZip2018_X] [numeric](10, 4) NULL,
	[SviHousingTypeTransportationPctlRankByZip2020_X] [numeric](10, 4) NULL,
	[SviHousingTypeTransportationPctlRankingByZip2018_X] [numeric](10, 4) NULL,
	[SviMinorityStatusLanguagePctlRankingByZip2018_X] [numeric](10, 4) NULL,
	[SviOverallPctlRankByZip2020_X] [numeric](10, 4) NULL,
	[SviOverallPctlRankingByZip2018_X] [numeric](10, 4) NULL,
	[SviRacialEthnicMinorityStatusPctlRankByZip2020_X] [numeric](10, 4) NULL,
	[SviSocioeconomicPctlRankByZip2020_X] [numeric](10, 4) NULL,
	[SviSocioeconomicPctlRankingByZip2018_X] [numeric](10, 4) NULL,
	[ADIUSPercentileRank] [smallint] NULL,
	[FoodWorry] [nvarchar](2500) NULL,
	[FoodWorryDateKey] [bigint] NULL,
	[AlcDrinksPerDay] [numeric](18, 2) NULL,
	[AlcDrinksPerDayDateKey] [bigint] NULL,
	[HistoryAlcUse] [nvarchar](2500) NULL,
	[HistoryAlcUseDateKey] [bigint] NULL,
	[CommDiseaseExp] [nvarchar](2500) NULL,
	[CommDiseaseExpDateKey] [bigint] NULL,
	[SocConnMember] [nvarchar](2500) NULL,
	[SocConnMemberDateKey] [bigint] NULL,
	[SocConnPhone] [nvarchar](2500) NULL,
	[SocConnPhoneDateKey] [bigint] NULL,
	[TransportMed] [nvarchar](2500) NULL,
	[TransportMedDateKey] [bigint] NULL,
	[CigPackYears] [numeric](18, 2) NULL,
	[CigPackYearsDateKey] [bigint] NULL,
	[BirthControl] [nvarchar](2500) NULL,
	[BirthControlDateKey] [bigint] NULL,
	[FoodScarcity] [nvarchar](2500) NULL,
	[FoodScarcityDateKey] [bigint] NULL,
	[SocConnGetTog] [nvarchar](2500) NULL,
	[SocConnGetTogDateKey] [bigint] NULL,
	[IPVPhysAbuse] [nvarchar](2500) NULL,
	[IPVPhysAbuseDateKey] [bigint] NULL,
	[TransportNonMed] [nvarchar](2500) NULL,
	[TransportNonMedDateKey] [bigint] NULL,
	[FreqDrugMisuse] [numeric](18, 2) NULL,
	[FreqDrugMisuseDateKey] [bigint] NULL,
	[CigPacksPerDay] [numeric](18, 2) NULL,
	[CigPacksPerDayDateKey] [bigint] NULL,
	[SmokingStatus] [nvarchar](2500) NULL,
	[SmokingStatusDateKey] [bigint] NULL,
	[PhysActivityDPW] [nvarchar](2500) NULL,
	[PhysActivityDPWDateKey] [bigint] NULL,
	[Stress] [nvarchar](2500) NULL,
	[StressDateKey] [bigint] NULL,
	[IPVEmotional] [nvarchar](2500) NULL,
	[IPVEmotionalDateKey] [bigint] NULL,
	[SocConnChurch] [nvarchar](2500) NULL,
	[SocConnChurchDateKey] [bigint] NULL,
	[PhysActivityMPS] [nvarchar](2500) NULL,
	[PhysActivityMPSDateKey] [bigint] NULL,
	[SmokelessStatus] [nvarchar](2500) NULL,
	[SmokelessStatusDateKey] [bigint] NULL,
	[AbusedSubstance] [nvarchar](2500) NULL,
	[AbusedSubstanceDateKey] [bigint] NULL,
	[SocConnLiving] [nvarchar](2500) NULL,
	[SocConnLivingDateKey] [bigint] NULL,
	[SexuallyActive] [nvarchar](2500) NULL,
	[SexuallyActiveDateKey] [bigint] NULL,
	[AlcStdDrinks] [nvarchar](2500) NULL,
	[AlcStdDrinksDateKey] [bigint] NULL,
	[IPVFear] [nvarchar](2500) NULL,
	[IPVFearDateKey] [bigint] NULL,
	[Financial] [nvarchar](2500) NULL,
	[FinancialDateKey] [bigint] NULL,
	[TobaccoUse] [nvarchar](2500) NULL,
	[TobaccoUseDateKey] [bigint] NULL,
	[TravelHistory] [nvarchar](2500) NULL,
	[TravelHistoryDateKey] [bigint] NULL,
	[AlcoholFreq] [nvarchar](2500) NULL,
	[AlcoholFreqDateKey] [bigint] NULL,
	[AlcoholBinge] [nvarchar](2500) NULL,
	[AlcoholBingeDateKey] [bigint] NULL,
	[IPVSexualAbuse] [nvarchar](2500) NULL,
	[IPVSexualAbuseDateKey] [bigint] NULL,
	[SubstUseStatus] [nvarchar](2500) NULL,
	[SubstUseStatusDateKey] [bigint] NULL,
	[SocConnMeetings] [nvarchar](2500) NULL,
	[SocConnMeetingsDateKey] [bigint] NULL,
	[SexualPartner] [nvarchar](2500) NULL,
	[SexualPartnerDateKey] [bigint] NULL,
	[HousingPlaceLived] [numeric](18, 2) NULL,
	[HousingPlaceLivedDateKey] [bigint] NULL,
	[HousingHomeless] [nvarchar](2500) NULL,
	[HousingHomelessDateKey] [bigint] NULL,
	[HousingMortgage] [nvarchar](2500) NULL,
	[HousingMortgageDateKey] [bigint] NULL,
	[AcutePain] [char](1) NULL,
	[Arthropathies] [char](1) NULL,
	[Cardiovascular] [char](1) NULL,
	[Chlamydia] [char](1) NULL,
	[ChronicFatigue] [char](1) NULL,
	[ChronicPain] [char](1) NULL,
	[Covid19] [char](1) NULL,
	[Dementing] [char](1) NULL,
	[Diabetes] [char](1) NULL,
	[GaitImp] [char](1) NULL,
	[Gonorrhea] [char](1) NULL,
	[Herpes] [char](1) NULL,
	[HIV] [char](1) NULL,
	[Neoplasms] [char](1) NULL,
	[Malnutrition] [char](1) NULL,
	[NervousSys] [char](1) NULL,
	[Obesity] [char](1) NULL,
	[PregnancyAbortive] [char](1) NULL,
	[SleepApnea] [char](1) NULL,
	[Syphilis] [char](1) NULL,
	[TBI] [char](1) NULL,
	[Weakness] [char](1) NULL,
	[Hospice] [char](1) NULL,
	[SuicideAttempt] [char](1) NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[BipolarDepression_EncLevelVars](
	[EncounterKey] [bigint] NOT NULL,
	[PatientDurableKey] [bigint] NULL,
	[EncDate] [date] NULL,
	[EncDateKey] [bigint] NULL,
	[AgeInDays] [int] NULL,
	[AgeInWeeks] [int] NULL,
	[AgeInMonths] [int] NULL,
	[AgeInYears] [int] NULL,
	[EncounterWeightLbs] [numeric](18, 2) NULL,
	[WeightGain10_20lbs] [char](1) NULL,
	[WeightGain20pluslbs] [char](1) NULL,
	[WeightLoss10_20lbs] [char](1) NULL,
	[WeightLoss20pluslbs] [char](1) NULL,
	[EncounterHeightInches] [numeric](18, 2) NULL,
	[EncounterBMI] [numeric](18, 2) NULL,
	[HealthInsLoss] [char](1) NULL,
	[MedicareYN] [char](1) NULL,
	[MedicaidYN] [char](1) NULL,
	[SelfPayYN] [char](1) NULL,
	[MiscOtherYN] [char](1) NULL,
	[PsychiatryVisitCount] [int] NULL,
	[PsychologyVisitCount] [int] NULL,
	[OutpatPrimaryDx] [nvarchar](max) NULL,
	[OutpatNonPrimaryDx] [nvarchar](max) NULL,
	[HxSuicideAttempt] [char](1) NULL,
	[Opioids] [char](1) NULL,
	[SSRI] [char](1) NULL,
	[Antipsychotics] [char](1) NULL,
	[Lithium] [char](1) NULL,
	[Anticonvulsants] [char](1) NULL,
	[Benzos] [char](1) NULL,
	[NRI] [char](1) NULL,
	[ADHDStimulants] [char](1) NULL,
	[Score5Score] [float] NULL,
	[Score5Level] [nvarchar](300) NULL,
	[Score5DateKey] [bigint] NULL,
	[Score49Score] [float] NULL,
	[Score49Level] [nvarchar](300) NULL,
	[Score49DateKey] [bigint] NULL,
	[Score50Score] [float] NULL,
	[Score50Level] [nvarchar](300) NULL,
	[Score50DateKey] [bigint] NULL,
	[Score51Score] [float] NULL,
	[Score51Level] [nvarchar](300) NULL,
	[Score51DateKey] [bigint] NULL,
	[Score52Score] [float] NULL,
	[Score52Level] [nvarchar](300) NULL,
	[Score52DateKey] [bigint] NULL,
	[Score53Score] [float] NULL,
	[Score53Level] [nvarchar](300) NULL,
	[Score53DateKey] [bigint] NULL,
	[Score54Score] [float] NULL,
	[Score54Level] [nvarchar](300) NULL,
	[Score54DateKey] [bigint] NULL,
	[Depression] [char](1) NULL,
	[DepressionPlus] [char](1) NULL,
	[MDDActive] [char](1) NULL,
	[MDDRemission] [char](1) NULL,
	[AnxietyPlus] [char](1) NULL,
	[Anxiety] [char](1) NULL,
	[AdjStressDisorder] [char](1) NULL,
	[MoodDisorders] [char](1) NULL,
	[PsychoticPlus] [char](1) NULL,
	[Schizophrenia] [char](1) NULL,
	[PersDisorders] [char](1) NULL,
	[MentalDisorder] [char](1) NULL,
	[EatingDisorder] [char](1) NULL,
	[SexualDysfunction] [char](1) NULL,
	[SleepDisorder] [char](1) NULL,
	[Autism] [char](1) NULL,
	[PTSD] [char](1) NULL,
	[PTSDPlus] [char](1) NULL,
	[ImpulseDisorders] [char](1) NULL,
	[ExternalizingDis] [char](1) NULL,
	[ADHD] [char](1) NULL,
	[MalignantNeoplasm] [char](1) NULL,
	[EDVisitCount] [int] NULL,
	[EDPrimDx] [nvarchar](max) NULL,
	[PainIntensityScore] [numeric](18, 2) NULL,
	[PainIntensityDateKey] [bigint] NULL,
	[VASScore] [numeric](18, 2) NULL,
	[VASDateKey] [bigint] NULL,
	[FatigueScore] [numeric](18, 2) NULL,
	[FatigueDateKey] [bigint] NULL,
	[PainInterfScore] [numeric](18, 2) NULL,
	[PainInterfDateKey] [bigint] NULL,
	[PxCount] [int] NULL,
	[PrescripMed45] [char](1) NULL,
	[PrescripMedGT5] [char](1) NULL,
	[Pulmonary] [smallint] NULL,
	[FastingGlucose] [smallint] NULL,
	[SpotGlucose] [smallint] NULL,
	[LipidLevels] [smallint] NULL,
	[CRP] [smallint] NULL,
	[Cortisol] [smallint] NULL,
	[Thyroid] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[EncounterKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[BipolarDepression_EncLevelVars_v2](
	[EncounterKey] [bigint] NOT NULL,
	[PatientDurableKey] [bigint] NULL,
	[EncDate] [date] NULL,
	[EncDateKey] [bigint] NULL,
	[AgeInDays] [int] NULL,
	[AgeInWeeks] [int] NULL,
	[AgeInMonths] [int] NULL,
	[AgeInYears] [int] NULL,
	[EncounterWeightLbs] [numeric](18, 2) NULL,
	[WeightGain10_20lbs] [char](1) NULL,
	[WeightGain20pluslbs] [char](1) NULL,
	[WeightLoss10_20lbs] [char](1) NULL,
	[WeightLoss20pluslbs] [char](1) NULL,
	[EncounterHeightInches] [numeric](18, 2) NULL,
	[EncounterBMI] [numeric](18, 2) NULL,
	[HealthInsLoss] [char](1) NULL,
	[MedicareYN] [char](1) NULL,
	[MedicaidYN] [char](1) NULL,
	[SelfPayYN] [char](1) NULL,
	[MiscOtherYN] [char](1) NULL,
	[PsychiatryVisitCount] [int] NULL,
	[PsychologyVisitCount] [int] NULL,
	[OutpatPrimaryDx] [nvarchar](max) NULL,
	[OutpatNonPrimaryDx] [nvarchar](max) NULL,
	[HxSuicideAttempt] [char](1) NULL,
	[Opioids] [char](1) NULL,
	[SSRI] [char](1) NULL,
	[Antipsychotics] [char](1) NULL,
	[Lithium] [char](1) NULL,
	[Anticonvulsants] [char](1) NULL,
	[Benzos] [char](1) NULL,
	[NRI] [char](1) NULL,
	[ADHDStimulants] [char](1) NULL,
	[Score5Score] [float] NULL,
	[Score5Level] [nvarchar](300) NULL,
	[Score5DateKey] [bigint] NULL,
	[Score49Score] [float] NULL,
	[Score49Level] [nvarchar](300) NULL,
	[Score49DateKey] [bigint] NULL,
	[Score50Score] [float] NULL,
	[Score50Level] [nvarchar](300) NULL,
	[Score50DateKey] [bigint] NULL,
	[Score51Score] [float] NULL,
	[Score51Level] [nvarchar](300) NULL,
	[Score51DateKey] [bigint] NULL,
	[Score52Score] [float] NULL,
	[Score52Level] [nvarchar](300) NULL,
	[Score52DateKey] [bigint] NULL,
	[Score53Score] [float] NULL,
	[Score53Level] [nvarchar](300) NULL,
	[Score53DateKey] [bigint] NULL,
	[Score54Score] [float] NULL,
	[Score54Level] [nvarchar](300) NULL,
	[Score54DateKey] [bigint] NULL,
	[Depression] [char](1) NULL,
	[DepressionPlus] [char](1) NULL,
	[MDDActive] [char](1) NULL,
	[MDDRemission] [char](1) NULL,
	[AnxietyPlus] [char](1) NULL,
	[Anxiety] [char](1) NULL,
	[AdjStressDisorder] [char](1) NULL,
	[MoodDisorders] [char](1) NULL,
	[PsychoticPlus] [char](1) NULL,
	[Schizophrenia] [char](1) NULL,
	[PersDisorders] [char](1) NULL,
	[MentalDisorder] [char](1) NULL,
	[EatingDisorder] [char](1) NULL,
	[SexualDysfunction] [char](1) NULL,
	[SleepDisorder] [char](1) NULL,
	[Autism] [char](1) NULL,
	[PTSD] [char](1) NULL,
	[PTSDPlus] [char](1) NULL,
	[ImpulseDisorders] [char](1) NULL,
	[ExternalizingDis] [char](1) NULL,
	[ADHD] [char](1) NULL,
	[MalignantNeoplasm] [char](1) NULL,
	[EDVisitCount] [int] NULL,
	[EDPrimDx] [nvarchar](max) NULL,
	[PainIntensityScore] [numeric](18, 2) NULL,
	[PainIntensityDateKey] [bigint] NULL,
	[VASScore] [numeric](18, 2) NULL,
	[VASDateKey] [bigint] NULL,
	[FatigueScore] [numeric](18, 2) NULL,
	[FatigueDateKey] [bigint] NULL,
	[PainInterfScore] [numeric](18, 2) NULL,
	[PainInterfDateKey] [bigint] NULL,
	[PxCount] [int] NULL,
	[PrescripMed45] [char](1) NULL,
	[PrescripMedGT5] [char](1) NULL,
	[Pulmonary] [smallint] NULL,
	[FastingGlucose] [smallint] NULL,
	[SpotGlucose] [smallint] NULL,
	[LipidLevels] [smallint] NULL,
	[CRP] [smallint] NULL,
	[Cortisol] [smallint] NULL,
	[Thyroid] [smallint] NULL,
	[CurrentSuicideAttempt] char(1) NULL,
PRIMARY KEY CLUSTERED 
(
	[EncounterKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
;

CREATE TABLE ProjectD52021F.[dbo].[BipolarDepression_EncLevelVars_v3](
	[EncounterKey] [bigint] NOT NULL,
	[PatientDurableKey] [bigint] NULL,
	[EncDate] [date] NULL,
	[EncDateKey] [bigint] NULL,
	[AgeInDays] [int] NULL,
	[AgeInWeeks] [int] NULL,
	[AgeInMonths] [int] NULL,
	[AgeInYears] [int] NULL,
	[EncounterWeightLbs] [numeric](18, 2) NULL,
	[WeightGain10_20lbs] [char](1) NULL,
	[WeightGain20pluslbs] [char](1) NULL,
	[WeightLoss10_20lbs] [char](1) NULL,
	[WeightLoss20pluslbs] [char](1) NULL,
	[EncounterHeightInches] [numeric](18, 2) NULL,
	[EncounterBMI] [numeric](18, 2) NULL,
	[HealthInsLoss] [char](1) NULL,
	[MedicareYN] [char](1) NULL,
	[MedicaidYN] [char](1) NULL,
	[SelfPayYN] [char](1) NULL,
	[MiscOtherYN] [char](1) NULL,
	[PsychiatryVisitCount] [int] NULL,
	[PsychologyVisitCount] [int] NULL,
	[OutpatPrimaryDx] [nvarchar](max) NULL,
	[OutpatNonPrimaryDx] [nvarchar](max) NULL,
	[HxSuicideAttempt] [char](1) NULL,
	[Opioids] [char](1) NULL,
	[SSRI] [char](1) NULL,
	[Antipsychotics] [char](1) NULL,
	[Lithium] [char](1) NULL,
	[Anticonvulsants] [char](1) NULL,
	[Benzos] [char](1) NULL,
	[NRI] [char](1) NULL,
	[ADHDStimulants] [char](1) NULL,
	[Score5Score] [float] NULL,
	[Score5Level] [nvarchar](300) NULL,
	[Score5DateKey] [bigint] NULL,
	[Score49Score] [float] NULL,
	[Score49Level] [nvarchar](300) NULL,
	[Score49DateKey] [bigint] NULL,
	[Score50Score] [float] NULL,
	[Score50Level] [nvarchar](300) NULL,
	[Score50DateKey] [bigint] NULL,
	[Score51Score] [float] NULL,
	[Score51Level] [nvarchar](300) NULL,
	[Score51DateKey] [bigint] NULL,
	[Score52Score] [float] NULL,
	[Score52Level] [nvarchar](300) NULL,
	[Score52DateKey] [bigint] NULL,
	[Score53Score] [float] NULL,
	[Score53Level] [nvarchar](300) NULL,
	[Score53DateKey] [bigint] NULL,
	[Score54Score] [float] NULL,
	[Score54Level] [nvarchar](300) NULL,
	[Score54DateKey] [bigint] NULL,
	[Depression] [char](1) NULL,
	[DepressionPlus] [char](1) NULL,
	[MDDActive] [char](1) NULL,
	[MDDRemission] [char](1) NULL,
	[AnxietyPlus] [char](1) NULL,
	[Anxiety] [char](1) NULL,
	[AdjStressDisorder] [char](1) NULL,
	[MoodDisorders] [char](1) NULL,
	[PsychoticPlus] [char](1) NULL,
	[Schizophrenia] [char](1) NULL,
	[PersDisorders] [char](1) NULL,
	[MentalDisorder] [char](1) NULL,
	[EatingDisorder] [char](1) NULL,
	[SexualDysfunction] [char](1) NULL,
	[SleepDisorder] [char](1) NULL,
	[Autism] [char](1) NULL,
	[PTSD] [char](1) NULL,
	[PTSDPlus] [char](1) NULL,
	[ImpulseDisorders] [char](1) NULL,
	[ExternalizingDis] [char](1) NULL,
	[ADHD] [char](1) NULL,
	[MalignantNeoplasm] [char](1) NULL,
	[EDVisitCount] [int] NULL,
	[EDPrimDx] [nvarchar](max) NULL,
	[PainIntensityScore] [numeric](18, 2) NULL,
	[PainIntensityDateKey] [bigint] NULL,
	[VASScore] [numeric](18, 2) NULL,
	[VASDateKey] [bigint] NULL,
	[FatigueScore] [numeric](18, 2) NULL,
	[FatigueDateKey] [bigint] NULL,
	[PainInterfScore] [numeric](18, 2) NULL,
	[PainInterfDateKey] [bigint] NULL,
	[PxCount] [int] NULL,
	[PrescripMed45] [char](1) NULL,
	[PrescripMedGT5] [char](1) NULL,
	[Pulmonary] [smallint] NULL,
	[FastingGlucose] [smallint] NULL,
	[SpotGlucose] [smallint] NULL,
	[LipidLevels] [smallint] NULL,
	[CRP] [smallint] NULL,
	[Cortisol] [smallint] NULL,
	[Thyroid] [smallint] NULL,
	[CurrentSuicideAttempt] char(1) NULL,
	HxSuicideAttempt30DaysPrior char(1) NULL,
	HxSuicideAttempt60DaysPrior char(1) NULL
PRIMARY KEY CLUSTERED 
(
	[EncounterKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE ProjectD52021F.[dbo].[BipolarDepression_AddlVarsOct2025](
	[PatientDurableKey] [bigint] NULL,
	[EncounterKey] [bigint] NOT NULL PRIMARY KEY,
	[EncDate] [date] NULL,
	HxSuicideAttempt30DaysPrior char(1),
	HxSuicideAttempt60DaysPrior char(1)
)
;